import type {
  Account,
  AuditLogEntry,
  BusinessDomain,
  BusinessTerm,
  Company,
  CompanyProduct,
  DataProductDefinition,
  DatasetEntityType,
  DateGranularity,
  DimensionDefinition,
  FilterOperator,
  FunnelEvent,
  MediaCampaign,
  MediaTouchpoint,
  MetricDefinition,
  Partner,
  Product,
  QualityStatus,
  Conversation,
  CRMInteraction,
  DigitalEvent,
  AppNavigationEvent,
  NpsResponse,
  Transaction,
} from '@bfp/domain';

const CATALOG_OWNER = 'Governança de Dados BFP';
const CATALOG_UPDATED_AT = '2026-10-07T00:00:00.000Z';
const CATALOG_VERSION = '1.0.0';

type DatasetEntityModelMap = {
  company: Company;
  partner: Partner;
  account: Account;
  product: Product;
  companyProduct: CompanyProduct;
  campaign: MediaCampaign;
  touchpoint: MediaTouchpoint;
  funnelEvent: FunnelEvent;
  crmInteraction: CRMInteraction;
  conversation: Conversation;
  digitalEvent: DigitalEvent;
  appNavigation: AppNavigationEvent;
  transaction: Transaction;
  npsResponse: NpsResponse;
  qualityStatus: QualityStatus;
  auditLog: AuditLogEntry;
};

/** Typed reference to a real field from one of the governed dataset entities. */
export type SourceFieldRef = {
  [T in keyof DatasetEntityModelMap]: {
    entityType: T;
    field: Extract<keyof DatasetEntityModelMap[T], string>;
  };
}[keyof DatasetEntityModelMap];

/** Extra governance metadata carried by the semantic metric catalog. */
export type GovernedMetricDefinition = MetricDefinition & {
  baseEntity: DatasetEntityType;
  sourceFields: readonly SourceFieldRef[];
  category: string;
  tags: readonly string[];
  bakedFilters?: readonly {
    field: string;
    operator: FilterOperator;
    value?: unknown;
    reason: string;
  }[];
  supportsTemporalGrouping?: boolean;
  /** Highlighted in the curated data library of the playground. */
  featured?: boolean;
  /** Position in the curated data library. */
  libraryOrder?: number;
};

/** Extra governance metadata carried by the semantic dimension catalog. */
export interface GovernedDimensionDefinition extends DimensionDefinition {
  label: string;
  baseEntity: DatasetEntityType;
  sourceFields: readonly SourceFieldRef[];
  ordering: number;
  supportedGranularities?: readonly DateGranularity[];
  /** Highlighted in the curated data library of the playground. */
  featured?: boolean;
  /** Position in the curated data library. */
  libraryOrder?: number;
  /** Business-friendly labels for enumerated raw values. */
  valueLabels?: Readonly<Record<string, string>>;
}

/** Data product enriched with the starter semantic surface it exposes. */
export interface GovernedDataProductDefinition extends DataProductDefinition {
  metricIds: readonly string[];
  dimensionIds: readonly string[];
  /** Business-friendly name of the curated (Gold) dataset. */
  goldDataset: string;
  /** Physical Gold table registered in the Glue Data Catalog. */
  goldTable: string;
  /** Upstream business systems feeding the data product. */
  businessSources: readonly string[];
}

const fieldRef = <T extends keyof DatasetEntityModelMap>(
  entityType: T,
  field: Extract<keyof DatasetEntityModelMap[T], string>,
): SourceFieldRef => ({ entityType, field }) as unknown as SourceFieldRef;

const defineDimensions = <const T extends readonly GovernedDimensionDefinition[]>(entries: T) =>
  entries;
const defineMetrics = <const T extends readonly GovernedMetricDefinition[]>(entries: T) => entries;
const defineDataProducts = <const T extends readonly GovernedDataProductDefinition[]>(entries: T) =>
  entries;
const defineGlossary = <const T extends readonly BusinessTerm[]>(entries: T) => entries;
const defineDomains = <const T extends readonly BusinessDomain[]>(entries: T) => entries;

const categoricalOperators = [
  'EQ',
  'NEQ',
  'IN',
  'NOT_IN',
  'IS_NULL',
  'IS_NOT_NULL',
] satisfies readonly FilterOperator[];
const searchableStringOperators = [
  'EQ',
  'NEQ',
  'IN',
  'NOT_IN',
  'CONTAINS',
  'IS_NULL',
  'IS_NOT_NULL',
] satisfies readonly FilterOperator[];
const dateOperators = [
  'EQ',
  'NEQ',
  'IN',
  'NOT_IN',
  'GT',
  'GTE',
  'LT',
  'LTE',
  'BETWEEN',
  'IS_NULL',
  'IS_NOT_NULL',
] satisfies readonly FilterOperator[];
const DATE_GRANULARITIES = ['date', 'week', 'month'] as const satisfies readonly DateGranularity[];

const COMPANY_CONTEXT_DIMENSIONS = [
  'segment',
  'industry',
  'company_size',
  'state',
  'region',
  'acquisition_source',
  'acquisition_channel',
  'acquisition_campaign',
  'company_status',
  'lead_date',
] as const;

const MEDIA_CONTEXT_DIMENSIONS = [
  'segment',
  'company_size',
  'state',
  'region',
  'acquisition_channel',
  'acquisition_campaign',
  'campaign_channel',
  'campaign_objective',
  'touchpoint_date',
] as const;

const ACTIVATION_CONTEXT_DIMENSIONS = [
  'segment',
  'company_size',
  'state',
  'region',
  'acquisition_source',
  'acquisition_channel',
  'acquisition_campaign',
  'company_status',
  'lead_date',
  'account_opened_date',
  'onboarding_completed_date',
  'activation_date',
] as const;

const PRODUCT_CONTEXT_DIMENSIONS = [
  'segment',
  'company_size',
  'state',
  'region',
  'acquisition_channel',
  'product',
  'product_category',
  'contracted_date',
] as const;

const CONVERSATION_CONTEXT_DIMENSIONS = [
  'segment',
  'company_size',
  'state',
  'region',
  'acquisition_channel',
  'conversation_status',
  'conversation_channel',
] as const;

const APP_CONTEXT_DIMENSIONS = [
  'segment',
  'company_size',
  'state',
  'region',
  'acquisition_channel',
  'app_screen',
  'app_action',
  'app_platform',
  'app_event_date',
] as const;

const TRANSACTION_CONTEXT_DIMENSIONS = [
  'segment',
  'industry',
  'company_size',
  'state',
  'region',
  'transaction_type',
  'transaction_channel',
  'transaction_date',
] as const;

const NPS_CONTEXT_DIMENSIONS = [
  'segment',
  'company_size',
  'state',
  'region',
  'acquisition_channel',
  'nps_touchpoint',
  'nps_date',
] as const;

export const DIMENSION_CATALOG = defineDimensions([
  {
    id: 'segment',
    label: 'Segmento',
    name: 'Segmento',
    description: 'Segmento principal da empresa para análises comerciais e de produto.',
    type: 'string',
    domain: 'customer360',
    source: 'company.segment',
    allowedOperators: [...searchableStringOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'segment')],
    ordering: 10,
    featured: true,
    libraryOrder: 3,
  },
  {
    id: 'industry',
    label: 'Indústria',
    name: 'Indústria',
    description: 'Indústria declarada pela empresa no cadastro sintético.',
    type: 'string',
    domain: 'customer360',
    source: 'company.industry',
    allowedOperators: [...searchableStringOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'industry')],
    ordering: 20,
  },
  {
    id: 'company_size',
    label: 'Porte da empresa',
    name: 'Porte da empresa',
    description: 'Faixa de porte usada para comparar comportamento por tamanho de empresa.',
    type: 'enum',
    domain: 'customer360',
    source: 'company.companySize',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'companySize')],
    ordering: 30,
    featured: true,
    libraryOrder: 4,
  },
  {
    id: 'state',
    label: 'Estado',
    name: 'Estado',
    description: 'UF da empresa para análises geográficas e comparação regional.',
    type: 'string',
    domain: 'customer360',
    source: 'company.state',
    allowedOperators: [...searchableStringOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'state')],
    ordering: 40,
    featured: true,
    libraryOrder: 5,
  },
  {
    id: 'region',
    label: 'Região',
    name: 'Região',
    description: 'Região agregada da empresa para cortes geográficos amplos.',
    type: 'string',
    domain: 'customer360',
    source: 'company.region',
    allowedOperators: [...searchableStringOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'region')],
    ordering: 50,
    featured: true,
    libraryOrder: 6,
  },
  {
    id: 'acquisition_source',
    label: 'Origem de aquisição',
    name: 'Origem de aquisição',
    description: 'Origem macro da aquisição da empresa, como paga, orgânica ou parceria.',
    type: 'enum',
    domain: 'acquisition',
    source: 'company.acquisitionSource',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'acquisitionSource')],
    ordering: 60,
    valueLabels: {
      PAID: 'Mídia paga',
      ORGANIC: 'Orgânico',
      REFERRAL: 'Indicação',
      PARTNER: 'Parceiros',
      OUTBOUND: 'Outbound',
    },
  },
  {
    id: 'acquisition_channel',
    label: 'Canal',
    name: 'Canal de aquisição',
    description: 'Canal principal atribuído à empresa para avaliar eficiência de aquisição.',
    type: 'enum',
    domain: 'acquisition',
    source: 'company.acquisitionChannel',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'acquisitionChannel')],
    ordering: 70,
    featured: true,
    libraryOrder: 1,
    valueLabels: {
      GOOGLE_SEARCH: 'Google Search',
      LINKEDIN: 'LinkedIn',
      META: 'Meta',
      ORGANIC: 'Organic',
      REFERRAL: 'Referral',
      EMAIL: 'E-mail',
      INSIDE_SALES: 'Inside Sales',
    },
  },
  {
    id: 'acquisition_campaign',
    label: 'Campanha',
    name: 'Campanha de aquisição',
    description: 'Campanha associada à aquisição da empresa quando existe atribuição conhecida.',
    type: 'string',
    domain: 'media',
    source: 'company.acquisitionCampaignId',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'acquisitionCampaignId')],
    ordering: 80,
    featured: true,
    libraryOrder: 2,
  },
  {
    id: 'company_status',
    label: 'Status da empresa',
    name: 'Status da empresa',
    description: 'Status atual da empresa ao longo do funil de aquisição e relacionamento.',
    type: 'enum',
    domain: 'customer360',
    source: 'company.status',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'status')],
    ordering: 90,
    valueLabels: {
      LEAD: 'Lead',
      ACCOUNT_OPENING: 'Abrindo conta',
      ONBOARDING: 'Em onboarding',
      ACTIVE: 'Ativa',
      INACTIVE: 'Inativa',
    },
  },
  {
    id: 'lead_date',
    label: 'Data do lead',
    name: 'Data do lead',
    description: 'Data de criação do lead, com suporte a dia, semana ou mês.',
    type: 'date',
    domain: 'acquisition',
    source: 'company.leadCreatedAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'leadCreatedAt')],
    ordering: 100,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'touchpoint_date',
    label: 'Data do touchpoint',
    name: 'Data do touchpoint',
    description: 'Data do evento de mídia para análises de spend, impressões e cliques.',
    type: 'date',
    domain: 'media',
    source: 'touchpoint.occurredAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'touchpoint',
    sourceFields: [fieldRef('touchpoint', 'occurredAt')],
    ordering: 110,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'account_opened_date',
    label: 'Data de abertura de conta',
    name: 'Data de abertura de conta',
    description: 'Data em que a empresa teve a conta aberta no fluxo sintético.',
    type: 'date',
    domain: 'acquisition',
    source: 'company.accountOpenedAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'accountOpenedAt')],
    ordering: 120,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'onboarding_completed_date',
    label: 'Data de onboarding concluído',
    name: 'Data de onboarding concluído',
    description: 'Data de conclusão do onboarding para cortes temporais de ativação.',
    type: 'date',
    domain: 'customer360',
    source: 'company.onboardingCompletedAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'onboardingCompletedAt')],
    ordering: 130,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'activation_date',
    label: 'Data de ativação',
    name: 'Data de ativação',
    description: 'Data em que a empresa ativou o uso após abertura e onboarding.',
    type: 'date',
    domain: 'customer360',
    source: 'company.activationDate',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'activationDate')],
    ordering: 140,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'campaign_channel',
    label: 'Canal da campanha',
    name: 'Canal da campanha',
    description: 'Canal configurado na campanha de mídia para análises de performance.',
    type: 'enum',
    domain: 'media',
    source: 'campaign.channel',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'campaign',
    sourceFields: [fieldRef('campaign', 'channel')],
    ordering: 150,
    valueLabels: {
      GOOGLE_SEARCH: 'Google Search',
      LINKEDIN: 'LinkedIn',
      META: 'Meta',
      ORGANIC: 'Organic',
      REFERRAL: 'Referral',
      EMAIL: 'E-mail',
      INSIDE_SALES: 'Inside Sales',
    },
  },
  {
    id: 'campaign_objective',
    label: 'Objetivo da campanha',
    name: 'Objetivo da campanha',
    description: 'Objetivo declarado da campanha para comparar estratégias de mídia.',
    type: 'enum',
    domain: 'media',
    source: 'campaign.objective',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'campaign',
    sourceFields: [fieldRef('campaign', 'objective')],
    ordering: 160,
    valueLabels: {
      LEAD_GENERATION: 'Geração de leads',
      AWARENESS: 'Reconhecimento',
      RETARGETING: 'Retargeting',
    },
  },
  {
    id: 'product',
    label: 'Produto',
    name: 'Produto',
    description:
      'Produto contratado pela empresa, resolvido pelo vínculo companyProduct → product.',
    type: 'string',
    domain: 'products',
    source: 'companyProduct.productId -> product.name',
    allowedOperators: [...searchableStringOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'companyProduct',
    sourceFields: [fieldRef('companyProduct', 'productId'), fieldRef('product', 'name')],
    ordering: 170,
    featured: true,
    libraryOrder: 7,
  },
  {
    id: 'product_category',
    label: 'Categoria do produto',
    name: 'Categoria do produto',
    description: 'Categoria semântica do produto para leitura macro do portfólio contratado.',
    type: 'enum',
    domain: 'products',
    source: 'companyProduct.productId -> product.category',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'companyProduct',
    sourceFields: [fieldRef('companyProduct', 'productId'), fieldRef('product', 'category')],
    ordering: 180,
    valueLabels: {
      BANKING: 'Conta e serviços',
      CREDIT: 'Crédito',
      PAYMENTS: 'Pagamentos',
      INSURANCE: 'Seguros',
      BENEFITS: 'Benefícios',
    },
  },
  {
    id: 'conversation_status',
    label: 'Status da conversa',
    name: 'Status da conversa',
    description: 'Status operacional da conversa usada em narrativas de resolução.',
    type: 'enum',
    domain: 'customer360',
    source: 'conversation.status',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'conversation',
    sourceFields: [fieldRef('conversation', 'status')],
    ordering: 190,
    valueLabels: { OPEN: 'Aberta', RESOLVED: 'Resolvida', ESCALATED: 'Escalada' },
  },
  {
    id: 'conversation_channel',
    label: 'Canal da conversa',
    name: 'Canal da conversa',
    description: 'Canal em que a conversa foi registrada com o cliente.',
    type: 'enum',
    domain: 'customer360',
    source: 'conversation.channel',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'conversation',
    sourceFields: [fieldRef('conversation', 'channel')],
    ordering: 200,
    valueLabels: { WHATSAPP: 'WhatsApp', CHAT: 'Chat', EMAIL: 'E-mail', PHONE: 'Telefone' },
  },
  {
    id: 'contracted_date',
    label: 'Data de contratação do produto',
    name: 'Data de contratação do produto',
    description: 'Data de contratação do produto, com granularidade temporal governada.',
    type: 'date',
    domain: 'products',
    source: 'companyProduct.contractedAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'companyProduct',
    sourceFields: [fieldRef('companyProduct', 'contractedAt')],
    ordering: 210,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'app_screen',
    label: 'Tela do app',
    name: 'Tela do app',
    description: 'Tela do app Itaú Empresas em que a interação aconteceu.',
    type: 'enum',
    domain: 'customer360',
    source: 'appNavigation.screen',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'screen')],
    ordering: 220,
    valueLabels: {
      HOME: 'Início',
      EXTRATO: 'Extrato',
      PIX: 'Pix',
      BOLETOS: 'Boletos',
      CARTOES: 'Cartões',
      INVESTIMENTOS: 'Investimentos',
      CREDITO: 'Crédito',
      FOLHA_PAGAMENTO: 'Folha de pagamento',
      MAQUININHA: 'Maquininha',
      PERFIL: 'Perfil',
    },
  },
  {
    id: 'app_action',
    label: 'Ação no app',
    name: 'Ação no app',
    description:
      'Tipo de interação registrada na tela: visualização, clique, conclusão, abandono ou erro.',
    type: 'enum',
    domain: 'customer360',
    source: 'appNavigation.action',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'action')],
    ordering: 230,
    valueLabels: {
      VIEW: 'Visualização',
      CLICK: 'Clique',
      COMPLETE: 'Conclusão',
      ABANDON: 'Abandono',
      ERROR: 'Erro',
    },
  },
  {
    id: 'app_platform',
    label: 'Plataforma do app',
    name: 'Plataforma do app',
    description: 'Sistema operacional do aparelho que usou o app Itaú Empresas.',
    type: 'enum',
    domain: 'customer360',
    source: 'appNavigation.platform',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'platform')],
    ordering: 240,
    valueLabels: { IOS: 'iOS', ANDROID: 'Android' },
  },
  {
    id: 'app_event_date',
    label: 'Data de uso do app',
    name: 'Data de uso do app',
    description: 'Data da interação no app, com granularidade temporal governada.',
    type: 'date',
    domain: 'customer360',
    source: 'appNavigation.occurredAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'occurredAt')],
    ordering: 250,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'transaction_type',
    label: 'Tipo de transação',
    name: 'Tipo de transação',
    description: 'Pix recebido/enviado, boleto emitido/pago, TED ou compra no cartão.',
    type: 'enum',
    domain: 'products',
    source: 'transaction.transactionType',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'transaction',
    sourceFields: [fieldRef('transaction', 'transactionType')],
    ordering: 260,
    valueLabels: {
      PIX_IN: 'Pix recebido',
      PIX_OUT: 'Pix enviado',
      BOLETO_ISSUED: 'Boleto emitido',
      BOLETO_PAID: 'Boleto pago',
      TED: 'TED',
      CARD_PURCHASE: 'Compra no cartão',
    },
  },
  {
    id: 'transaction_channel',
    label: 'Canal da transação',
    name: 'Canal da transação',
    description: 'Canal em que a transação foi iniciada.',
    type: 'enum',
    domain: 'products',
    source: 'transaction.channel',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'transaction',
    sourceFields: [fieldRef('transaction', 'channel')],
    ordering: 270,
    valueLabels: {
      APP: 'App',
      INTERNET_BANKING: 'Internet Banking',
      API: 'API',
      AGENCY: 'Agência',
    },
  },
  {
    id: 'transaction_date',
    label: 'Data da transação',
    name: 'Data da transação',
    description: 'Data da transação, com granularidade temporal governada.',
    type: 'date',
    domain: 'products',
    source: 'transaction.occurredAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'transaction',
    sourceFields: [fieldRef('transaction', 'occurredAt')],
    ordering: 280,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
  {
    id: 'nps_touchpoint',
    label: 'Momento da pesquisa NPS',
    name: 'Momento da pesquisa NPS',
    description: 'Ponto da relação em que a pesquisa NPS foi respondida.',
    type: 'enum',
    domain: 'customer360',
    source: 'npsResponse.touchpoint',
    allowedOperators: [...categoricalOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'npsResponse',
    sourceFields: [fieldRef('npsResponse', 'touchpoint')],
    ordering: 290,
    valueLabels: {
      ONBOARDING: 'Onboarding',
      APP: 'App',
      SERVICE: 'Atendimento',
      RELATIONSHIP_MANAGER: 'Gerente de relacionamento',
    },
  },
  {
    id: 'nps_date',
    label: 'Data da resposta NPS',
    name: 'Data da resposta NPS',
    description: 'Data da resposta à pesquisa NPS, com granularidade temporal governada.',
    type: 'date',
    domain: 'customer360',
    source: 'npsResponse.respondedAt',
    allowedOperators: [...dateOperators],
    sensitivity: 'INTERNAL',
    certificationStatus: 'CERTIFIED',
    baseEntity: 'npsResponse',
    sourceFields: [fieldRef('npsResponse', 'respondedAt')],
    ordering: 300,
    supportedGranularities: [...DATE_GRANULARITIES],
  },
] satisfies readonly GovernedDimensionDefinition[]);

const ALL_DIMENSION_IDS = DIMENSION_CATALOG.map((dimension) => dimension.id);

const companyFilters = [fieldRef('company', 'id')] as const;
/** Governed catalog of the 23 initial metrics required by the MVP architecture. */
export const METRIC_CATALOG = defineMetrics([
  {
    id: 'companies_total',
    name: 'Empresas totais',
    shortName: 'Empresas',
    description: 'Quantidade total de empresas no conjunto filtrado.',
    businessDefinition:
      'Conta empresas distintas disponíveis após filtros e escopo temporal aplicados.',
    formula: 'COUNT_DISTINCT(company.id)',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'customer360',
    owner: 'Clientes PJ',
    source: 'company.id',
    timeField: 'createdAt',
    allowedDimensions: [...COMPANY_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'DEPRECATED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [...companyFilters, fieldRef('company', 'createdAt')],
    category: 'Volume',
    tags: ['empresas', 'base', 'customer360'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'new_companies',
    name: 'Novos clientes PJ',
    shortName: 'Novos clientes PJ',
    description: 'Empresas que se tornaram clientes PJ (onboarding concluído) no período.',
    businessDefinition:
      'Conta empresas distintas que concluíram abertura de conta e onboarding, pela data de conclusão do onboarding.',
    formula: 'COUNT_DISTINCT(company.id) WHERE company.onboardingCompletedAt IS NOT NULL',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    source: 'company.id, company.onboardingCompletedAt',
    timeField: 'onboardingCompletedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [...companyFilters, fieldRef('company', 'onboardingCompletedAt')],
    category: 'Aquisição',
    tags: ['aquisição', 'clientes', 'onboarding'],
    bakedFilters: [
      {
        field: 'onboarding_completed_date',
        operator: 'IS_NOT_NULL',
        reason: 'Somente empresas com onboarding concluído viram clientes.',
      },
    ],
    supportsTemporalGrouping: true,
    featured: true,
    libraryOrder: 3,
  },
  {
    id: 'leads',
    name: 'Leads',
    shortName: 'Leads',
    description: 'Empresas que entraram no funil comercial como lead.',
    businessDefinition: 'Conta empresas distintas com data de criação de lead conhecida.',
    formula: 'COUNT_DISTINCT(company.id) WHERE company.leadCreatedAt IS NOT NULL',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    source: 'company.id, company.leadCreatedAt',
    timeField: 'leadCreatedAt',
    allowedDimensions: [...COMPANY_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [...companyFilters, fieldRef('company', 'leadCreatedAt')],
    category: 'Aquisição',
    tags: ['lead', 'funil', 'aquisição'],
    bakedFilters: [
      {
        field: 'lead_date',
        operator: 'IS_NOT_NULL',
        reason: 'A métrica conta apenas empresas que efetivamente viraram lead.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'accounts_opened',
    name: 'Contas abertas',
    shortName: 'Contas abertas',
    description: 'Empresas que concluíram a abertura de conta.',
    businessDefinition: 'Conta empresas distintas com data de abertura de conta preenchida.',
    formula: 'COUNT_DISTINCT(company.id) WHERE company.accountOpenedAt IS NOT NULL',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    source: 'company.id, company.accountOpenedAt',
    timeField: 'accountOpenedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [...companyFilters, fieldRef('company', 'accountOpenedAt')],
    category: 'Aquisição',
    tags: ['conta', 'conversão', 'aquisição'],
    bakedFilters: [
      {
        field: 'account_opened_date',
        operator: 'IS_NOT_NULL',
        reason: 'A métrica conta apenas empresas com conta aberta.',
      },
    ],
    supportsTemporalGrouping: true,
    featured: true,
    libraryOrder: 5,
  },
  {
    id: 'converted_leads',
    name: 'Leads convertidos em conta',
    shortName: 'Leads convertidos',
    description: 'Leads criados no período que concluíram a abertura de conta.',
    businessDefinition:
      'Conta empresas distintas cujo lead foi criado no período e que já possuem conta aberta.',
    formula:
      'COUNT_DISTINCT(company.id) WHERE company.accountOpenedAt IS NOT NULL por company.leadCreatedAt',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    source: 'company.id, company.leadCreatedAt, company.accountOpenedAt',
    timeField: 'leadCreatedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 15,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [
      ...companyFilters,
      fieldRef('company', 'leadCreatedAt'),
      fieldRef('company', 'accountOpenedAt'),
    ],
    category: 'Conversão',
    tags: ['conversão', 'funil', 'coorte'],
    bakedFilters: [
      {
        field: 'account_opened_date',
        operator: 'IS_NOT_NULL',
        reason: 'Somente leads que já abriram conta entram no numerador.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'account_conversion_rate',
    name: 'Conversão de abertura',
    shortName: 'Conversão de abertura',
    description:
      'Percentual de empresas que efetivamente concluíram a abertura de conta em relação à população elegível considerada pela métrica.',
    businessDefinition:
      'Indica a eficiência da jornada de aquisição até a conta aberta. Considera empresas elegíveis no período selecionado e aplica os mesmos recortes ao numerador e ao denominador.',
    formula: 'converted_leads / leads',
    aggregation: 'RATIO',
    format: 'percent',
    unit: '%',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    source: 'Métrica derivada de converted_leads e leads (coorte do lead)',
    timeField: 'leadCreatedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: '2.1',
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'converted_leads',
    denominator: 'leads',
    baseEntity: 'company',
    sourceFields: [
      ...companyFilters,
      fieldRef('company', 'leadCreatedAt'),
      fieldRef('company', 'accountOpenedAt'),
    ],
    category: 'Conversão',
    tags: ['conversão', 'funil', 'aquisição'],
    supportsTemporalGrouping: true,
    featured: true,
    libraryOrder: 1,
  },
  {
    id: 'media_spend',
    name: 'Investimento em mídia',
    shortName: 'Investimento em mídia',
    description: 'Valor total investido em touchpoints de mídia no período.',
    businessDefinition: 'Soma o custo registrado nos touchpoints de mídia.',
    formula: 'SUM(touchpoint.cost)',
    aggregation: 'SUM',
    format: 'currency',
    unit: 'BRL',
    domain: 'media',
    owner: 'Mídia PJ',
    source: 'touchpoint.cost',
    timeField: 'occurredAt',
    allowedDimensions: [...MEDIA_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.99,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'touchpoint',
    sourceFields: [
      fieldRef('touchpoint', 'cost'),
      fieldRef('touchpoint', 'occurredAt'),
      fieldRef('touchpoint', 'campaignId'),
    ],
    category: 'Mídia',
    tags: ['mídia', 'investimento', 'performance'],
    supportsTemporalGrouping: true,
    featured: true,
    libraryOrder: 6,
  },
  {
    id: 'impressions',
    name: 'Impressões',
    shortName: 'Impressões',
    description: 'Quantidade total de impressões registradas nos touchpoints de mídia.',
    businessDefinition: 'Soma as impressões capturadas em cada touchpoint.',
    formula: 'SUM(touchpoint.impressions)',
    aggregation: 'SUM',
    format: 'number',
    domain: 'media',
    owner: 'Mídia PJ',
    source: 'touchpoint.impressions',
    timeField: 'occurredAt',
    allowedDimensions: [...MEDIA_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.99,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'touchpoint',
    sourceFields: [
      fieldRef('touchpoint', 'impressions'),
      fieldRef('touchpoint', 'occurredAt'),
      fieldRef('touchpoint', 'campaignId'),
    ],
    category: 'Mídia',
    tags: ['mídia', 'alcance', 'performance'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'clicks',
    name: 'Cliques',
    shortName: 'Cliques',
    description: 'Quantidade total de cliques registrados nos touchpoints de mídia.',
    businessDefinition: 'Soma os cliques capturados em cada touchpoint.',
    formula: 'SUM(touchpoint.clicks)',
    aggregation: 'SUM',
    format: 'number',
    domain: 'media',
    owner: 'Mídia PJ',
    source: 'touchpoint.clicks',
    timeField: 'occurredAt',
    allowedDimensions: [...MEDIA_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.99,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'touchpoint',
    sourceFields: [
      fieldRef('touchpoint', 'clicks'),
      fieldRef('touchpoint', 'occurredAt'),
      fieldRef('touchpoint', 'campaignId'),
    ],
    category: 'Mídia',
    tags: ['mídia', 'tráfego', 'performance'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'ctr',
    name: 'CTR',
    shortName: 'CTR',
    description: 'Percentual de cliques sobre impressões no mesmo recorte.',
    businessDefinition:
      'Divide cliques por impressões para medir eficiência do criativo e da segmentação.',
    formula: 'clicks / impressions',
    aggregation: 'RATIO',
    format: 'percent',
    unit: '%',
    domain: 'media',
    owner: 'Mídia PJ',
    source: 'Métrica derivada de clicks e impressions',
    timeField: 'occurredAt',
    allowedDimensions: [...MEDIA_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'clicks',
    denominator: 'impressions',
    baseEntity: 'touchpoint',
    sourceFields: [
      fieldRef('touchpoint', 'clicks'),
      fieldRef('touchpoint', 'impressions'),
      fieldRef('touchpoint', 'occurredAt'),
    ],
    category: 'Eficiência de mídia',
    tags: ['mídia', 'ctr', 'eficiência'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'cpl',
    name: 'CPL',
    shortName: 'CPL',
    description: 'Custo por lead no mesmo recorte semântico.',
    businessDefinition: 'Divide investimento em mídia pelo número de leads atribuídos ao recorte.',
    formula: 'media_spend / leads',
    aggregation: 'RATIO',
    format: 'currency',
    unit: 'BRL',
    domain: 'media',
    owner: 'Mídia PJ',
    source: 'Métrica derivada de media_spend e leads',
    timeField: 'occurredAt',
    allowedDimensions: [...MEDIA_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'media_spend',
    denominator: 'leads',
    baseEntity: 'touchpoint',
    sourceFields: [
      fieldRef('touchpoint', 'cost'),
      fieldRef('touchpoint', 'occurredAt'),
      fieldRef('company', 'leadCreatedAt'),
    ],
    category: 'Eficiência de aquisição',
    tags: ['mídia', 'cpl', 'aquisição'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'cac',
    name: 'CAC',
    shortName: 'CAC',
    description: 'Custo de aquisição por empresa com conta aberta.',
    businessDefinition: 'Divide investimento em mídia por contas abertas no mesmo grão e recorte.',
    formula: 'media_spend / accounts_opened',
    aggregation: 'RATIO',
    format: 'currency',
    unit: 'BRL',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    source: 'Métrica derivada de media_spend e accounts_opened',
    timeField: 'accountOpenedAt',
    allowedDimensions: [
      ...ACTIVATION_CONTEXT_DIMENSIONS,
      'campaign_channel',
      'campaign_objective',
      'touchpoint_date',
    ],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'media_spend',
    denominator: 'accounts_opened',
    baseEntity: 'company',
    sourceFields: [
      fieldRef('touchpoint', 'cost'),
      fieldRef('touchpoint', 'occurredAt'),
      fieldRef('company', 'accountOpenedAt'),
    ],
    category: 'Eficiência de aquisição',
    tags: ['cac', 'aquisição', 'eficiência'],
    supportsTemporalGrouping: true,
    featured: true,
    libraryOrder: 2,
  },
  {
    id: 'onboarding_started',
    name: 'Onboardings iniciados',
    shortName: 'Onboardings iniciados',
    description: 'Empresas que iniciaram onboarding no período.',
    businessDefinition: 'Conta empresas distintas com data de início de onboarding preenchida.',
    formula: 'COUNT_DISTINCT(company.id) WHERE company.onboardingStartedAt IS NOT NULL',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'customer360',
    owner: 'Onboarding PJ',
    source: 'company.id, company.onboardingStartedAt',
    timeField: 'onboardingStartedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [...companyFilters, fieldRef('company', 'onboardingStartedAt')],
    category: 'Onboarding',
    tags: ['onboarding', 'ativação', 'journey'],
    bakedFilters: [
      {
        field: 'onboarding_completed_date',
        operator: 'IS_NOT_NULL',
        reason: 'Usada em conjunto com métricas de conclusão e ativação.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'onboarding_completed',
    name: 'Onboardings concluídos',
    shortName: 'Onboardings concluídos',
    description: 'Empresas que concluíram onboarding no período.',
    businessDefinition: 'Conta empresas distintas com data de conclusão de onboarding preenchida.',
    formula: 'COUNT_DISTINCT(company.id) WHERE company.onboardingCompletedAt IS NOT NULL',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'customer360',
    owner: 'Onboarding PJ',
    source: 'company.id, company.onboardingCompletedAt',
    timeField: 'onboardingCompletedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [...companyFilters, fieldRef('company', 'onboardingCompletedAt')],
    category: 'Onboarding',
    tags: ['onboarding', 'conclusão', 'journey'],
    bakedFilters: [
      {
        field: 'onboarding_completed_date',
        operator: 'IS_NOT_NULL',
        reason: 'A métrica conta apenas empresas com onboarding concluído.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'onboarding_completion_rate',
    name: 'Taxa de conclusão de onboarding',
    shortName: 'Conclusão onboarding',
    description: 'Percentual de onboardings iniciados que chegaram à conclusão.',
    businessDefinition: 'Divide onboardings concluídos por onboardings iniciados no mesmo recorte.',
    formula: 'onboarding_completed / onboarding_started',
    aggregation: 'RATIO',
    format: 'percent',
    unit: '%',
    domain: 'customer360',
    owner: 'Onboarding PJ',
    source: 'Métrica derivada de onboarding_completed e onboarding_started',
    timeField: 'onboardingCompletedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'onboarding_completed',
    denominator: 'onboarding_started',
    baseEntity: 'company',
    sourceFields: [
      fieldRef('company', 'onboardingStartedAt'),
      fieldRef('company', 'onboardingCompletedAt'),
    ],
    category: 'Onboarding',
    tags: ['onboarding', 'conversão', 'ativação'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'activation_d30',
    name: 'Ativações D30',
    shortName: 'Ativações D30',
    description: 'Empresas que ativaram em até 30 dias após a abertura de conta.',
    businessDefinition:
      'Conta empresas cuja data de ativação ocorre até 30 dias depois da abertura da conta.',
    formula:
      'COUNT_DISTINCT(company.id) WHERE DATEDIFF(day, company.accountOpenedAt, company.activationDate) <= 30',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'customer360',
    owner: 'Onboarding PJ',
    source: 'company.id, company.accountOpenedAt, company.activationDate',
    timeField: 'activationDate',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [
      ...companyFilters,
      fieldRef('company', 'accountOpenedAt'),
      fieldRef('company', 'activationDate'),
    ],
    category: 'Ativação',
    tags: ['ativação', 'd30', 'customer360'],
    bakedFilters: [
      {
        field: 'activation_date',
        operator: 'IS_NOT_NULL',
        reason: 'A métrica exige data de ativação conhecida.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'activation_d30_rate',
    name: 'Ativação D30',
    shortName: 'Ativação D30',
    description: 'Percentual de contas abertas que ativaram em até 30 dias.',
    businessDefinition: 'Divide ativações D30 por contas abertas no mesmo recorte.',
    formula: 'activation_d30 / accounts_opened',
    aggregation: 'RATIO',
    format: 'percent',
    unit: '%',
    domain: 'customer360',
    owner: 'Onboarding PJ',
    source: 'Métrica derivada de activation_d30 e accounts_opened',
    timeField: 'activationDate',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'activation_d30',
    denominator: 'accounts_opened',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'accountOpenedAt'), fieldRef('company', 'activationDate')],
    category: 'Ativação',
    tags: ['ativação', 'd30', 'conversão'],
    supportsTemporalGrouping: true,
    featured: true,
    libraryOrder: 4,
  },
  {
    id: 'active_companies',
    name: 'Empresas ativas',
    shortName: 'Ativas',
    description: 'Empresas cujo status atual é ACTIVE.',
    businessDefinition: 'Conta empresas distintas com status ACTIVE no recorte filtrado.',
    formula: "COUNT_DISTINCT(company.id) WHERE company.status = 'ACTIVE'",
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'customer360',
    owner: 'Clientes PJ',
    source: 'company.id, company.status',
    timeField: 'activationDate',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'company',
    sourceFields: [
      ...companyFilters,
      fieldRef('company', 'status'),
      fieldRef('company', 'activationDate'),
    ],
    category: 'Base ativa',
    tags: ['customer360', 'ativo', 'base'],
    bakedFilters: [
      {
        field: 'company_status',
        operator: 'EQ',
        value: 'ACTIVE',
        reason: 'A métrica representa apenas empresas com status ativo.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'products_per_company',
    name: 'Produtos por cliente',
    shortName: 'Produtos por cliente',
    description: 'Média de produtos contratados por empresa no recorte.',
    businessDefinition:
      'Calcula a média de vínculos companyProduct ativos ou contratados por empresa distinta.',
    formula: 'AVG(active_company_products_per_company)',
    aggregation: 'AVG',
    format: 'number',
    domain: 'products',
    owner: 'Produtos PJ',
    source: 'companyProduct.companyId, companyProduct.productId, companyProduct.status',
    timeField: 'contractedAt',
    allowedDimensions: [...PRODUCT_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    baseEntity: 'companyProduct',
    sourceFields: [
      fieldRef('companyProduct', 'companyId'),
      fieldRef('companyProduct', 'productId'),
      fieldRef('companyProduct', 'status'),
      fieldRef('companyProduct', 'contractedAt'),
    ],
    category: 'Produtos',
    tags: ['cross-sell', 'produtos', 'portfólio'],
    bakedFilters: [
      {
        field: 'company_status',
        operator: 'NOT_IN',
        value: ['LEAD'],
        reason: 'A métrica é interpretada sobre empresas com relacionamento já iniciado.',
      },
    ],
    supportsTemporalGrouping: false,
    featured: true,
    libraryOrder: 7,
  },
  {
    id: 'average_opening_time',
    name: 'Tempo médio de abertura',
    shortName: 'Tempo de abertura',
    description: 'Tempo médio, em dias, entre a criação do lead e a abertura da conta.',
    businessDefinition: 'Mede a eficiência operacional do fluxo comercial até a abertura.',
    formula: 'AVG(DATEDIFF(day, company.leadCreatedAt, company.accountOpenedAt))',
    aggregation: 'AVG',
    format: 'number',
    unit: 'dias',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    source: 'company.leadCreatedAt, company.accountOpenedAt',
    timeField: 'accountOpenedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    baseEntity: 'company',
    sourceFields: [fieldRef('company', 'leadCreatedAt'), fieldRef('company', 'accountOpenedAt')],
    category: 'Eficiência operacional',
    tags: ['tempo', 'abertura', 'sla'],
    supportsTemporalGrouping: false,
  },
  {
    id: 'average_onboarding_time',
    name: 'Tempo médio de onboarding',
    shortName: 'Tempo de onboarding',
    description: 'Tempo médio, em dias, entre o início e a conclusão do onboarding.',
    businessDefinition: 'Mede o tempo operacional necessário para concluir o onboarding.',
    formula: 'AVG(DATEDIFF(day, company.onboardingStartedAt, company.onboardingCompletedAt))',
    aggregation: 'AVG',
    format: 'number',
    unit: 'dias',
    domain: 'customer360',
    owner: 'Onboarding PJ',
    source: 'company.onboardingStartedAt, company.onboardingCompletedAt',
    timeField: 'onboardingCompletedAt',
    allowedDimensions: [...ACTIVATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    baseEntity: 'company',
    sourceFields: [
      fieldRef('company', 'onboardingStartedAt'),
      fieldRef('company', 'onboardingCompletedAt'),
    ],
    category: 'Eficiência operacional',
    tags: ['tempo', 'onboarding', 'sla'],
    supportsTemporalGrouping: false,
  },
  {
    id: 'revenue_proxy',
    name: 'Receita proxy',
    shortName: 'Receita proxy',
    description: 'Soma do valor proxy mensal gerado pelos produtos contratados.',
    businessDefinition: 'Soma o monthlyRevenueProxy dos produtos com status ACTIVE ou CONTRACTED.',
    formula: 'SUM(companyProduct.monthlyRevenueProxy)',
    aggregation: 'SUM',
    format: 'currency',
    unit: 'BRL',
    domain: 'products',
    owner: 'Produtos PJ',
    source: 'companyProduct.monthlyRevenueProxy',
    timeField: 'contractedAt',
    allowedDimensions: [...PRODUCT_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.98,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'companyProduct',
    sourceFields: [
      fieldRef('companyProduct', 'monthlyRevenueProxy'),
      fieldRef('companyProduct', 'status'),
      fieldRef('companyProduct', 'contractedAt'),
    ],
    category: 'Receita',
    tags: ['receita', 'proxy', 'produtos'],
    bakedFilters: [
      {
        field: 'product',
        operator: 'IS_NOT_NULL',
        reason: 'A métrica depende de um vínculo válido entre empresa e produto.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'campaign_conversion_rate',
    name: 'Taxa de conversão da campanha',
    shortName: 'Conversão campanha',
    description: 'Percentual de cliques que resultam em contas abertas no recorte de campanha.',
    businessDefinition:
      'Divide contas abertas pelos cliques atribuídos ao mesmo contexto de campanha.',
    formula: 'accounts_opened / clicks',
    aggregation: 'RATIO',
    format: 'percent',
    unit: '%',
    domain: 'media',
    owner: 'Mídia PJ',
    source: 'Métrica derivada de accounts_opened e clicks',
    timeField: 'occurredAt',
    allowedDimensions: [...MEDIA_CONTEXT_DIMENSIONS, 'lead_date', 'account_opened_date'],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'accounts_opened',
    denominator: 'clicks',
    baseEntity: 'touchpoint',
    sourceFields: [
      fieldRef('touchpoint', 'clicks'),
      fieldRef('touchpoint', 'campaignId'),
      fieldRef('company', 'accountOpenedAt'),
    ],
    category: 'Conversão de mídia',
    tags: ['mídia', 'campanha', 'conversão'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'unresolved_conversations',
    name: 'Conversas não resolvidas',
    shortName: 'Não resolvidas',
    description: 'Quantidade de conversas abertas ou escaladas ainda sem resolução.',
    businessDefinition: 'Conta conversas cujo status final não é RESOLVED.',
    formula: "COUNT(conversation.id) WHERE conversation.status IN ('OPEN', 'ESCALATED')",
    aggregation: 'COUNT',
    format: 'number',
    domain: 'customer360',
    owner: 'Atendimento PJ',
    source: 'conversation.id, conversation.status',
    timeField: 'startedAt',
    allowedDimensions: [...CONVERSATION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.97,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'conversation',
    sourceFields: [
      fieldRef('conversation', 'id'),
      fieldRef('conversation', 'status'),
      fieldRef('conversation', 'startedAt'),
    ],
    category: 'Atendimento',
    tags: ['conversa', 'resolução', 'customer360'],
    bakedFilters: [
      {
        field: 'conversation_status',
        operator: 'NOT_IN',
        value: ['RESOLVED'],
        reason: 'A métrica representa somente conversas ainda sem resolução.',
      },
    ],
    supportsTemporalGrouping: true,
  },
  {
    id: 'app_interactions',
    name: 'Interações no app',
    shortName: 'Interações no app',
    description:
      'Quantidade de interações (telas, cliques, conclusões, abandonos e erros) no app Itaú Empresas.',
    businessDefinition: 'Conta os eventos de navegação registrados pela telemetria do app.',
    formula: 'COUNT(appNavigation.id)',
    aggregation: 'COUNT',
    format: 'number',
    domain: 'customer360',
    owner: 'Canais Digitais PJ',
    source: 'appNavigation.id',
    timeField: 'occurredAt',
    allowedDimensions: [...APP_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'id'), fieldRef('appNavigation', 'occurredAt')],
    category: 'Uso do app',
    tags: ['app', 'navegação', 'digital'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'app_sessions',
    name: 'Sessões no app',
    shortName: 'Sessões no app',
    description: 'Quantidade de sessões distintas no app Itaú Empresas.',
    businessDefinition: 'Conta sessões distintas (sessionId) da telemetria do app.',
    formula: 'COUNT_DISTINCT(appNavigation.sessionId)',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'customer360',
    owner: 'Canais Digitais PJ',
    source: 'appNavigation.sessionId',
    timeField: 'occurredAt',
    allowedDimensions: [...APP_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'sessionId')],
    category: 'Uso do app',
    tags: ['app', 'sessão', 'digital'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'app_active_companies',
    name: 'Empresas ativas no app',
    shortName: 'Ativas no app',
    description: 'Empresas distintas que usaram o app Itaú Empresas no período.',
    businessDefinition: 'Conta empresas com pelo menos uma interação no app.',
    formula: 'COUNT_DISTINCT(appNavigation.companyId)',
    aggregation: 'COUNT_DISTINCT',
    format: 'number',
    domain: 'customer360',
    owner: 'Canais Digitais PJ',
    source: 'appNavigation.companyId',
    timeField: 'occurredAt',
    allowedDimensions: [...APP_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'companyId')],
    category: 'Uso do app',
    tags: ['app', 'engajamento', 'digital'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'app_avg_screen_time',
    name: 'Tempo médio por tela',
    shortName: 'Tempo por tela',
    description: 'Tempo médio, em segundos, que a empresa passa em cada tela do app.',
    businessDefinition: 'Média de durationSeconds dos eventos de navegação do app.',
    formula: 'AVG(appNavigation.durationSeconds)',
    aggregation: 'AVG',
    format: 'number',
    unit: 'segundos',
    domain: 'customer360',
    owner: 'Canais Digitais PJ',
    source: 'appNavigation.durationSeconds',
    timeField: 'occurredAt',
    allowedDimensions: [...APP_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'EXPERIMENTAL',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'durationSeconds')],
    category: 'Uso do app',
    tags: ['app', 'tempo', 'ux'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'app_errors',
    name: 'Erros no app',
    shortName: 'Erros no app',
    description: 'Interações do app que terminaram em erro.',
    businessDefinition: 'Conta eventos de navegação com ação ERROR.',
    formula: "COUNT(appNavigation.id) WHERE appNavigation.action = 'ERROR'",
    aggregation: 'COUNT',
    format: 'number',
    domain: 'customer360',
    owner: 'Canais Digitais PJ',
    source: 'appNavigation.action',
    timeField: 'occurredAt',
    allowedDimensions: [...APP_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    bakedFilters: [
      {
        field: 'app_action',
        operator: 'EQ',
        value: 'ERROR',
        reason: 'A métrica conta apenas interações com erro.',
      },
    ],
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'id'), fieldRef('appNavigation', 'action')],
    category: 'Uso do app',
    tags: ['app', 'erro', 'qualidade'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'app_error_rate',
    name: 'Taxa de erro no app',
    shortName: 'Taxa de erro',
    description: 'Percentual das interações no app que terminaram em erro.',
    businessDefinition: 'Divide os erros no app pelo total de interações no app.',
    formula: 'app_errors / app_interactions',
    aggregation: 'RATIO',
    format: 'percent',
    unit: '%',
    domain: 'customer360',
    owner: 'Canais Digitais PJ',
    source: 'Métrica derivada de app_errors e app_interactions',
    timeField: 'occurredAt',
    allowedDimensions: [...APP_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'app_errors',
    denominator: 'app_interactions',
    baseEntity: 'appNavigation',
    sourceFields: [fieldRef('appNavigation', 'action')],
    category: 'Uso do app',
    tags: ['app', 'erro', 'qualidade'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'transaction_volume',
    name: 'Volume transacionado',
    shortName: 'Volume transacionado',
    description: 'Soma dos valores movimentados em Pix, boletos, TED e cartão.',
    businessDefinition: 'Soma o amount das transações das empresas.',
    formula: 'SUM(transaction.amount)',
    aggregation: 'SUM',
    format: 'currency',
    unit: 'BRL',
    domain: 'products',
    owner: 'Pagamentos PJ',
    source: 'transaction.amount',
    timeField: 'occurredAt',
    allowedDimensions: [...TRANSACTION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'transaction',
    sourceFields: [fieldRef('transaction', 'amount'), fieldRef('transaction', 'occurredAt')],
    category: 'Transações',
    tags: ['transações', 'pix', 'boleto'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'transactions_count',
    name: 'Quantidade de transações',
    shortName: 'Transações',
    description: 'Quantidade de transações realizadas pelas empresas.',
    businessDefinition: 'Conta as transações registradas.',
    formula: 'COUNT(transaction.id)',
    aggregation: 'COUNT',
    format: 'number',
    domain: 'products',
    owner: 'Pagamentos PJ',
    source: 'transaction.id',
    timeField: 'occurredAt',
    allowedDimensions: [...TRANSACTION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'transaction',
    sourceFields: [fieldRef('transaction', 'id')],
    category: 'Transações',
    tags: ['transações', 'pix', 'boleto'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'average_ticket',
    name: 'Ticket médio',
    shortName: 'Ticket médio',
    description: 'Valor médio por transação.',
    businessDefinition: 'Divide o volume transacionado pela quantidade de transações.',
    formula: 'transaction_volume / transactions_count',
    aggregation: 'RATIO',
    format: 'currency',
    unit: 'BRL',
    domain: 'products',
    owner: 'Pagamentos PJ',
    source: 'Métrica derivada de transaction_volume e transactions_count',
    timeField: 'occurredAt',
    allowedDimensions: [...TRANSACTION_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    numerator: 'transaction_volume',
    denominator: 'transactions_count',
    baseEntity: 'transaction',
    sourceFields: [fieldRef('transaction', 'amount')],
    category: 'Transações',
    tags: ['transações', 'ticket'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'nps_responses',
    name: 'Respostas NPS',
    shortName: 'Respostas NPS',
    description: 'Quantidade de respostas às pesquisas NPS.',
    businessDefinition: 'Conta as respostas de NPS (nota de 0 a 10).',
    formula: 'COUNT(npsResponse.id)',
    aggregation: 'COUNT',
    format: 'number',
    domain: 'customer360',
    owner: 'Experiência do Cliente PJ',
    source: 'npsResponse.id',
    timeField: 'respondedAt',
    allowedDimensions: [...NPS_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'ADDITIVE',
    baseEntity: 'npsResponse',
    sourceFields: [fieldRef('npsResponse', 'id')],
    category: 'Experiência',
    tags: ['nps', 'satisfação'],
    supportsTemporalGrouping: true,
  },
  {
    id: 'nps',
    name: 'NPS',
    shortName: 'NPS',
    description: 'Net Promoter Score: % de promotores (9-10) menos % de detratores (0-6).',
    businessDefinition: 'Calcula o NPS a partir das notas de 0 a 10 das pesquisas.',
    formula: '100 * (COUNT(score >= 9) - COUNT(score <= 6)) / COUNT(npsResponse.id)',
    aggregation: 'AVG',
    format: 'number',
    unit: 'pontos',
    domain: 'customer360',
    owner: 'Experiência do Cliente PJ',
    source: 'npsResponse.score',
    timeField: 'respondedAt',
    allowedDimensions: [...NPS_CONTEXT_DIMENSIONS],
    allowedFilters: [...ALL_DIMENSION_IDS],
    certificationStatus: 'CERTIFIED',
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.96,
    version: CATALOG_VERSION,
    updatedAt: CATALOG_UPDATED_AT,
    additivity: 'NON_ADDITIVE',
    baseEntity: 'npsResponse',
    sourceFields: [fieldRef('npsResponse', 'score')],
    category: 'Experiência',
    tags: ['nps', 'satisfação', 'promotores'],
    supportsTemporalGrouping: true,
  },
] satisfies readonly GovernedMetricDefinition[]);

/** Starter data products aligned with the governed semantic surface. */
export const DATA_PRODUCT_CATALOG = defineDataProducts([
  {
    id: 'customer360_profile',
    name: 'Customer 360',
    description: 'Visão unificada da empresa PJ: cadastro, porte, segmento, localidade e status.',
    domain: 'customer360',
    owner: 'Clientes PJ',
    sourceEntityTypes: ['company', 'partner', 'account'],
    freshnessSLOMinutes: 60,
    qualityThreshold: 0.98,
    lineage: {
      upstreamIds: ['company', 'partner', 'account'],
      downstreamIds: ['companies_total', 'active_companies'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: ['companies_total', 'active_companies'],
    dimensionIds: ['segment', 'industry', 'company_size', 'state', 'region', 'company_status'],
    goldDataset: 'Customer 360 Gold',
    goldTable: 'gold_customer_360',
    businessSources: ['Cadastro PJ', 'Abertura de contas'],
  },
  {
    id: 'acquisition_funnel',
    name: 'Acquisition',
    description: 'Consolida o funil de aquisição da empresa do lead até abertura e ativação.',
    domain: 'acquisition',
    owner: 'Acquisition PJ',
    sourceEntityTypes: ['company', 'touchpoint', 'campaign'],
    freshnessSLOMinutes: 15,
    qualityThreshold: 0.97,
    lineage: {
      upstreamIds: ['company', 'touchpoint', 'campaign'],
      downstreamIds: ['leads', 'accounts_opened', 'account_conversion_rate', 'cac'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: ['new_companies', 'leads', 'accounts_opened', 'account_conversion_rate', 'cac'],
    dimensionIds: [
      'acquisition_source',
      'acquisition_channel',
      'acquisition_campaign',
      'lead_date',
      'state',
    ],
    goldDataset: 'Acquisition Gold',
    goldTable: 'gold_acquisition_events',
    businessSources: ['CRM', 'Mídia', 'Abertura de contas'],
  },
  {
    id: 'media_performance',
    name: 'Media',
    description:
      'Performance de campanhas, investimento, impressões, cliques e eficiência de mídia.',
    domain: 'media',
    owner: 'Mídia PJ',
    sourceEntityTypes: ['touchpoint', 'campaign', 'company'],
    freshnessSLOMinutes: 60,
    qualityThreshold: 0.97,
    lineage: {
      upstreamIds: ['touchpoint', 'campaign'],
      downstreamIds: [
        'media_spend',
        'impressions',
        'clicks',
        'ctr',
        'cpl',
        'campaign_conversion_rate',
      ],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: ['media_spend', 'impressions', 'clicks', 'ctr', 'cpl', 'campaign_conversion_rate'],
    dimensionIds: [
      'acquisition_channel',
      'acquisition_campaign',
      'campaign_channel',
      'campaign_objective',
      'touchpoint_date',
    ],
    goldDataset: 'Media Gold',
    goldTable: 'gold_media',
    businessSources: ['Google Ads', 'Meta Ads', 'LinkedIn Ads'],
  },
  {
    id: 'customer360_activation',
    name: 'Onboarding',
    description: 'Monitora onboarding, ativação D30 e empresas ativas após a abertura de conta.',
    domain: 'customer360',
    owner: 'Onboarding PJ',
    sourceEntityTypes: ['company', 'funnelEvent'],
    freshnessSLOMinutes: 60,
    qualityThreshold: 0.96,
    lineage: {
      upstreamIds: ['company', 'funnelEvent'],
      downstreamIds: ['onboarding_completion_rate', 'activation_d30_rate'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: [
      'onboarding_started',
      'onboarding_completed',
      'onboarding_completion_rate',
      'activation_d30',
      'activation_d30_rate',
      'active_companies',
      'average_onboarding_time',
    ],
    dimensionIds: [
      'company_status',
      'account_opened_date',
      'onboarding_completed_date',
      'activation_date',
      'region',
    ],
    goldDataset: 'Onboarding Gold',
    goldTable: 'gold_onboarding',
    businessSources: ['Onboarding', 'Abertura de contas'],
  },
  {
    id: 'product_adoption_revenue',
    name: 'Products',
    description: 'Produtos contratados, penetração por cliente e receita proxy mensal.',
    domain: 'products',
    owner: 'Produtos PJ',
    sourceEntityTypes: ['companyProduct', 'product', 'company'],
    freshnessSLOMinutes: 240,
    qualityThreshold: 0.96,
    lineage: {
      upstreamIds: ['companyProduct', 'product'],
      downstreamIds: ['products_per_company', 'revenue_proxy'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: ['products_per_company', 'revenue_proxy'],
    dimensionIds: ['product', 'product_category', 'contracted_date', 'company_size', 'segment'],
    goldDataset: 'Products Gold',
    goldTable: 'gold_products',
    businessSources: ['Produtos PJ', 'Cartões PJ', 'Pix PJ'],
  },
  {
    id: 'crm_relationship',
    name: 'CRM',
    description: 'Interações comerciais e de relacionamento registradas no CRM Empresas.',
    domain: 'customer360',
    owner: 'Relacionamento PJ',
    sourceEntityTypes: ['crmInteraction', 'company'],
    freshnessSLOMinutes: 120,
    qualityThreshold: 0.95,
    lineage: {
      upstreamIds: ['crmInteraction'],
      downstreamIds: [],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: [],
    dimensionIds: ['segment', 'company_size', 'region'],
    goldDataset: 'CRM Gold',
    goldTable: 'gold_crm_interactions',
    businessSources: ['CRM Empresas'],
  },
  {
    id: 'conversations_service',
    name: 'Conversations',
    description: 'Conversas de atendimento e comerciais por canal, status e tempo de resolução.',
    domain: 'customer360',
    owner: 'Atendimento PJ',
    sourceEntityTypes: ['conversation', 'company'],
    freshnessSLOMinutes: 120,
    qualityThreshold: 0.95,
    lineage: {
      upstreamIds: ['conversation'],
      downstreamIds: ['unresolved_conversations'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: ['unresolved_conversations'],
    dimensionIds: ['conversation_status', 'conversation_channel'],
    goldDataset: 'Conversations Gold',
    goldTable: 'gold_conversations',
    businessSources: ['WhatsApp', 'Chat', 'Telefone'],
  },
  {
    id: 'app_navigation',
    name: 'App Itaú Empresas',
    description: 'Telemetria de navegação do app Itaú Empresas: telas, ações, plataforma e tempo.',
    domain: 'customer360',
    owner: 'Canais Digitais PJ',
    sourceEntityTypes: ['appNavigation', 'company'],
    freshnessSLOMinutes: 60,
    qualityThreshold: 0.96,
    lineage: {
      upstreamIds: ['appNavigation'],
      downstreamIds: ['app_interactions', 'app_sessions', 'app_active_companies', 'app_error_rate'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: [
      'app_interactions',
      'app_sessions',
      'app_active_companies',
      'app_avg_screen_time',
      'app_errors',
      'app_error_rate',
    ],
    dimensionIds: ['app_screen', 'app_action', 'app_platform', 'app_event_date'],
    goldDataset: 'App Navigation Gold',
    goldTable: 'app_navigation',
    businessSources: ['App Itaú Empresas (telemetria)'],
  },
  {
    id: 'payments_transactions',
    name: 'Transações',
    description: 'Pix, boletos, TED e cartão movimentados pelas empresas (valores agregáveis).',
    domain: 'products',
    owner: 'Pagamentos PJ',
    sourceEntityTypes: ['transaction', 'company'],
    freshnessSLOMinutes: 60,
    qualityThreshold: 0.98,
    lineage: {
      upstreamIds: ['transaction'],
      downstreamIds: ['transaction_volume', 'transactions_count', 'average_ticket'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: ['transaction_volume', 'transactions_count', 'average_ticket'],
    dimensionIds: ['transaction_type', 'transaction_channel', 'transaction_date'],
    goldDataset: 'Transactions Gold',
    goldTable: 'transactions',
    businessSources: ['Pix', 'Boletos', 'TED', 'Cartões PJ'],
  },
  {
    id: 'customer_experience_nps',
    name: 'NPS',
    description: 'Respostas às pesquisas NPS por momento da relação (sem texto livre).',
    domain: 'customer360',
    owner: 'Experiência do Cliente PJ',
    sourceEntityTypes: ['npsResponse', 'company'],
    freshnessSLOMinutes: 1440,
    qualityThreshold: 0.95,
    lineage: {
      upstreamIds: ['npsResponse'],
      downstreamIds: ['nps', 'nps_responses'],
    },
    updatedAt: CATALOG_UPDATED_AT,
    metricIds: ['nps', 'nps_responses'],
    dimensionIds: ['nps_touchpoint', 'nps_date'],
    goldDataset: 'NPS Gold',
    goldTable: 'nps_responses',
    businessSources: ['Pesquisas de satisfação (NPS)'],
  },
] satisfies readonly GovernedDataProductDefinition[]);

/** Starter glossary aligned with the semantic metric catalog for Explorer and Copilot grounding. */
export const BUSINESS_GLOSSARY = defineGlossary([
  {
    id: 'term_nps',
    term: 'NPS',
    definition:
      'Net Promoter Score: percentual de promotores (notas 9 e 10) menos o de detratores (0 a 6), de -100 a 100.',
    domain: 'customer360',
    owner: 'Experiência do Cliente PJ',
    synonyms: ['net promoter score', 'satisfação', 'recomendação'],
    relatedMetricIds: ['nps', 'nps_responses'],
    relatedDimensionIds: ['nps_touchpoint', 'company_size'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_cac',
    term: 'CAC',
    definition:
      'Custo de aquisição de cliente medido como investimento em mídia dividido por contas abertas.',
    domain: 'acquisition',
    owner: CATALOG_OWNER,
    synonyms: ['custo de aquisição', 'customer acquisition cost'],
    relatedMetricIds: ['cac'],
    relatedDimensionIds: ['acquisition_channel', 'company_size', 'state'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_cpl',
    term: 'CPL',
    definition:
      'Custo por lead calculado a partir do investimento em mídia sobre o volume de leads.',
    domain: 'media',
    owner: CATALOG_OWNER,
    synonyms: ['custo por lead'],
    relatedMetricIds: ['cpl'],
    relatedDimensionIds: ['acquisition_channel', 'acquisition_campaign'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_ctr',
    term: 'CTR',
    definition: 'Click-through rate: percentual de cliques em relação ao total de impressões.',
    domain: 'media',
    owner: CATALOG_OWNER,
    synonyms: ['taxa de clique'],
    relatedMetricIds: ['ctr'],
    relatedDimensionIds: ['campaign_channel', 'touchpoint_date'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_activation_d30',
    term: 'Ativação D30',
    definition: 'Empresa que ativou o uso em até 30 dias depois da abertura da conta.',
    domain: 'customer360',
    owner: CATALOG_OWNER,
    synonyms: ['ativação em 30 dias', 'd30'],
    relatedMetricIds: ['activation_d30', 'activation_d30_rate'],
    relatedDimensionIds: ['activation_date', 'company_size'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_onboarding',
    term: 'Onboarding',
    definition: 'Etapa de preparação da empresa para uso da conta e dos produtos.',
    domain: 'customer360',
    owner: CATALOG_OWNER,
    synonyms: ['implantação inicial'],
    relatedMetricIds: ['onboarding_started', 'onboarding_completed', 'onboarding_completion_rate'],
    relatedDimensionIds: ['onboarding_completed_date', 'company_status'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_revenue_proxy',
    term: 'Receita proxy',
    definition: 'Valor mensal estimado gerado pelos produtos contratados por uma empresa.',
    domain: 'products',
    owner: CATALOG_OWNER,
    synonyms: ['receita estimada', 'proxy de receita'],
    relatedMetricIds: ['revenue_proxy'],
    relatedDimensionIds: ['product', 'product_category'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_active_company',
    term: 'Empresa ativa',
    definition: 'Empresa com status ACTIVE no relacionamento com a plataforma.',
    domain: 'customer360',
    owner: CATALOG_OWNER,
    synonyms: ['cliente ativo'],
    relatedMetricIds: ['active_companies'],
    relatedDimensionIds: ['company_status', 'activation_date'],
    sensitivity: 'PUBLIC',
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: 'term_unresolved_conversation',
    term: 'Conversa não resolvida',
    definition: 'Conversa cujo status permanece OPEN ou ESCALATED e ainda exige ação operacional.',
    domain: 'customer360',
    owner: CATALOG_OWNER,
    synonyms: ['pendência de atendimento'],
    relatedMetricIds: ['unresolved_conversations'],
    relatedDimensionIds: ['conversation_status', 'conversation_channel'],
    sensitivity: 'INTERNAL',
    updatedAt: CATALOG_UPDATED_AT,
  },
] satisfies readonly BusinessTerm[]);

/** Supported business domains present in the semantic layer. */
export const SEMANTIC_DOMAINS = defineDomains([
  'media',
  'acquisition',
  'customer360',
  'products',
] satisfies readonly BusinessDomain[]);

export const METRIC_DEFINITION_BY_ID = new Map(METRIC_CATALOG.map((metric) => [metric.id, metric]));
export const DIMENSION_DEFINITION_BY_ID = new Map(
  DIMENSION_CATALOG.map((dimension) => [dimension.id, dimension]),
);
export const DATA_PRODUCT_BY_ID = new Map(
  DATA_PRODUCT_CATALOG.map((product) => [product.id, product]),
);
export const BUSINESS_TERM_BY_ID = new Map(BUSINESS_GLOSSARY.map((term) => [term.id, term]));

/** Returns a shallow copy of the supported semantic domains. */
export function listSemanticDomains(): BusinessDomain[] {
  return [...SEMANTIC_DOMAINS];
}

/** Looks up a governed metric by its stable semantic identifier. */
export function getMetricDefinition(id: string): GovernedMetricDefinition | undefined {
  return METRIC_DEFINITION_BY_ID.get(id);
}

/** Looks up a governed dimension by its stable semantic identifier. */
export function getDimensionDefinition(id: string): GovernedDimensionDefinition | undefined {
  return DIMENSION_DEFINITION_BY_ID.get(id);
}

/** Lists the governed metric catalog, optionally scoped to a single business domain. */
export function listMetricDefinitions(domain?: BusinessDomain): GovernedMetricDefinition[] {
  return domain ? METRIC_CATALOG.filter((metric) => metric.domain === domain) : [...METRIC_CATALOG];
}

/** Lists the governed dimension catalog, optionally scoped to a single business domain. */
export function listDimensionDefinitions(domain?: BusinessDomain): GovernedDimensionDefinition[] {
  return domain
    ? DIMENSION_CATALOG.filter((dimension) => dimension.domain === domain)
    : [...DIMENSION_CATALOG];
}

/** Checks whether a metric explicitly supports a given dimension. */
export function compatibility(metricId: string, dimensionId: string): boolean {
  const metric = getMetricDefinition(metricId);
  if (!metric) {
    return false;
  }

  if (metric.allowedDimensions === '*') {
    return true;
  }

  return metric.allowedDimensions.includes(dimensionId);
}

/** Utility set used by validation logic to detect temporal grouping requests. */
export const DATE_DIMENSION_IDS = new Set(
  DIMENSION_CATALOG.filter((dimension) => dimension.type === 'date').map(
    (dimension) => dimension.id,
  ),
);

/** Returns the governed data product that publishes a metric, when any. */
export function getDataProductForMetric(
  metricId: string,
): GovernedDataProductDefinition | undefined {
  return DATA_PRODUCT_CATALOG.find((product) =>
    (product.metricIds as readonly string[]).includes(metricId),
  );
}

/** Resolves a business-friendly label for a raw dimension value. */
export function resolveDimensionValueLabel(dimensionId: string, value: unknown): string {
  if (value === null || value === undefined || value === '') {
    return 'Não informado';
  }

  const raw = String(value);
  return getDimensionDefinition(dimensionId)?.valueLabels?.[raw] ?? raw;
}
